### ISSUE TITLE
GitHub Pages deployment failure after succeeding

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/codedoc#135]
In an attempt to remove a warning about my NPM lock file being created by a previous version of NPM, I updated NPM and then deleted and recreated my lock file (by calling `codedoc install`).  However, the [resulting lock file](https://github.com/TysonMN/tysonmn.github.io/commit/7a5a45ad482da077bff54ae7251228d702094aa3) lead to a [deployment failure](https://github.com/TysonMN/tysonmn.github.io/runs/8058853139?check_suite_focus=true).

Do you know why the deployment failed?

**Comment by TysonMN** [comment]
It wasn't NPM or the lock file.  I have updated the title of this issue accordingly.

For a certain commit, the [first deployment succeeded](https://github.com/TysonMN/tysonmn.github.io/actions/runs/2943632838/attempts/1) and the [second deployment failed](https://github.com/TysonMN/tysonmn.github.io/actions/runs/2943632838/attempts/2).  It is not consistently failing.

I have compared the logs.  In the successful case, the build step logs this:
```
# built:: ......... dist/dist/bundle/codedoc-bundle.js
# running after build hooks ...
# running ......... saveFeed()
# finished:: ...... saveFeed()
# Build Successful.
```

In the failure case, the build step logs this:
```
# building ........ dist/dist/bundle/codedoc-bundle.js
Hash: fabeacb28432a719832a
Version: webpack 4.46.0
Time: 7410ms
Built at: 09/08/2022 1:38:52 AM
            Asset     Size  Chunks  Chunk Names
codedoc-bundle.js  540 KiB       0  main
Entrypoint main = codedoc-bundle.js
  [6] ./.codedoc/node_modules/rxjs/_esm5/index.js + 35 modules 59.6 KiB {0} [built]
      | ./.codedoc/node_modules/rxjs/_esm5/index.js 3.33 KiB [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/operators/groupBy.js 6.59 KiB [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/scheduler/queue.js 312 bytes [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/operators/observeOn.js 2.56 KiB [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/ReplaySubject.js 4.36 KiB [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/AsyncSubject.js 1.59 KiB [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/scheduler/asap.js 300 bytes [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/scheduler/animationFrame.js 420 bytes [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/scheduler/VirtualTimeScheduler.js 3.58 KiB [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/util/isObservable.js 302 bytes [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/util/EmptyError.js 452 bytes [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/util/TimeoutError.js 465 bytes [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/observable/bindCallback.js 3.85 KiB [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/observable/bindNodeCallback.js 4.3 KiB [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/observable/forkJoin.js 2.59 KiB [built]
      |     + 21 hidden modules
  [9] ./.codedoc/node_modules/@connectv/core/dist/es6/index.js 125 bytes [built]
 [12] ./.codedoc/node_modules/@connectv/sdh/dist/es6/dynamic/transport/index.js + 1 modules 503 bytes {0} [built]
      | ./.codedoc/node_modules/@connectv/sdh/dist/es6/dynamic/transport/index.js 216 bytes [built]
      | ./.codedoc/node_modules/@connectv/sdh/dist/es6/static/types.js 267 bytes [built]
 [17] ./.codedoc/node_modules/jss/dist/jss.esm.js + 5 modules 57.3 KiB {0} [built]
      | ./.codedoc/node_modules/jss/dist/jss.esm.js 55.8 KiB [built]
      | ./.codedoc/node_modules/@babel/runtime/helpers/esm/createClass.js 579 bytes [built]
      | ./.codedoc/node_modules/@babel/runtime/helpers/esm/inheritsLoose.js 259 bytes [built]
      | ./.codedoc/node_modules/@babel/runtime/helpers/esm/assertThisInitialized.js 192 bytes [built]
      | ./.codedoc/node_modules/@babel/runtime/helpers/esm/objectWithoutPropertiesLoose.js 350 bytes [built]
      | ./.codedoc/node_modules/@babel/runtime/helpers/esm/setPrototypeOf.js 200 bytes [built]
 [20] ./.codedoc/node_modules/rxjs/_esm5/operators/index.js 6.15 KiB [built]
 [29] ./.codedoc/node_modules/@connectv/html/dist/es6/index.js + 6 modules 2.06 KiB {0} [built]
      | ./.codedoc/node_modules/@connectv/html/dist/es6/index.js 224 bytes [built]
      | ./.codedoc/node_modules/@connectv/html/dist/es6/typings/index.js 139 bytes [built]
      | ./.codedoc/node_modules/@connectv/html/dist/es6/components/index.js 181 bytes [built]
      | ./.codedoc/node_modules/@connectv/html/dist/es6/shared/index.js 199 bytes [built]
      | ./.codedoc/node_modules/@connectv/html/dist/es6/util/index.js 199 bytes [built]
      | ./.codedoc/node_modules/@connectv/html/dist/es6/components/conditional.js 865 bytes [built]
      | ./.codedoc/node_modules/@connectv/html/dist/es6/components/context.js 231 bytes [built]
 [43] ./.codedoc/node_modules/@connectv/jss-theme/dist/es6/index.js 90 bytes {0} [built]
[142] ./.codedoc/node_modules/color/index.js 10.9 KiB {0} [built]
[202] ./.codedoc/content/theme.ts 381 bytes {0} [built] [failed] [1 error]
[203] ./.codedoc/node_modules/@codedoc/coding-blog-plugin/dist/es5/components/article-card/count-cards.js 1 KiB {0} [built]
[204] ./.codedoc/components/SeeTypo/index.tsx 381 bytes {0} [built] [failed] [1 error]
[205] ./.codedoc/node_modules/@codedoc/coding-blog-plugin/dist/es5/components/author/index.js 3.15 KiB {0} [built]
[206] ./.codedoc/node_modules/@codedoc/coding-blog-plugin/dist/es5/components/article-card/index.js 4.18 KiB {0} [built]
[211] ./.codedoc/node_modules/@codedoc/core/dist/es6/components/darkmode/darklight/index.js 1.46 KiB [built]
[296] ./dist/dist/bundle/codedoc-bundle.entry.js + 73 modules 144 KiB {0} [built]
      | ./dist/dist/bundle/codedoc-bundle.entry.js 5.16 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/transport/renderer.js 500 bytes [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/transport/setup-jss.js 472 bytes [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/code/smart-copy.js 1.42 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/code/selection.js 5.03 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/code/same-line-length.js 818 bytes [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/code/line-hint/index.js 1.77 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/transport/config.js 359 bytes [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/code/line-ref/index.js 2.07 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/heading/copy-headings.js 1.89 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/page/contentnav/highlight.js 2.06 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/transport/deferred-iframe.js 607 bytes [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/transport/smooth-loading.js 4.66 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/page/toc/toc-highlight.js 1.33 KiB [built]
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/page/toc/search/post-nav/index.js 3.76 KiB [built]
      |     + 59 hidden modules
    + 412 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in ./.codedoc/content/theme.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/home/runner/work/tysonmn.github.io/tysonmn.github.io/node_modules/ts-loader/dist/index.js:91:41)
    at Object.loader (/home/runner/work/tysonmn.github.io/tysonmn.github.io/node_modules/ts-loader/dist/index.js:14:21)
 @ ./dist/dist/bundle/codedoc-bundle.entry.js 3:0-[111](https://github.com/TysonMN/tysonmn.github.io/runs/8240438714?check_suite_focus=true#step:3:112) 3:111-123

ERROR in ./.codedoc/components/SeeTypo/index.tsx
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/home/runner/work/tysonmn.github.io/tysonmn.github.io/node_modules/ts-loader/dist/index.js:91:41)
    at Object.loader (/home/runner/work/tysonmn.github.io/tysonmn.github.io/node_modules/ts-loader/dist/index.js:14:21)
 @ ./dist/dist/bundle/codedoc-bundle.entry.js 19:0-[118](https://github.com/TysonMN/tysonmn.github.io/runs/8240438714?check_suite_focus=true#step:3:119) 30:30-37
# Build Failed.

Error: Process completed with exit code 1.
```

**Comment by loreanvictor** [comment]
@TysonMN yes this is the result of out of date dependencies. Update codedoc (`codedoc update latest`) should fix this issue, at least for a clean CI build. On your local machine, if the issue persists after updating codedoc, I would recommend checking if `ts-node` or `ts-node-dev` are installed globally, and updating them if they are.

**Comment by TysonMN** [comment]
I hadn't tested locally (but of course I should have).  I didn't experience that issue locally (though I had to fix an asset path issue with this commit).

I updated `cli`, `core`, and `coding-blog-plugin` for `codedoc`, and now [the GitHub deployment](https://github.com/TysonMN/tysonmn.github.io/runs/8285455831?check_suite_focus=true) worked!  Thanks :D

P.S.
Though now I can't build locally: #137.
