### ISSUE TITLE
Local build not working: TypeError: merge is not a function

### ISSUE THREAD

**Issue by TysonMN** [CONNECT-platform/codedoc#137]
This happens when I try to locally serve [my site](https://github.com/TysonMN/tysonmn.github.io).  Everything (`cli`, `core`, `coding-blog-plugin`, `ts-node-dev`, `ts-node`, `npm`, `typescript`) is updated to the latest version.

```
twilliams@EDMONDS MINGW64 /c/Code/Blogs/tyson-williams-blog (next)
$ npm -v
8.19.1

twilliams@EDMONDS MINGW64 /c/Code/Blogs/tyson-williams-blog (next)
$ codedoc version

# Fetching version info ...
# @codedoc/cli version 0.3.0 ...................................... latest: 0.3.0
# @codedoc/core version: 0.3.1 .................................... latest: 0.3.1

twilliams@EDMONDS MINGW64 /c/Code/Blogs/tyson-williams-blog (next)
$ codedoc serve

# Serving ...
# Fetching project configuration ...
[INFO] 09:51:36 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 4.8.3)
TypeError: merge is not a function
    at serve (C:\Code\Blogs\tyson-williams-blog\.codedoc\node_modules\@codedoc\core\src\serve\index.ts:39:18)
    at Object.<anonymous> (C:\Code\Blogs\tyson-williams-blog\.codedoc\serve.ts:11:6)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module._compile (C:\Users\twilliams\AppData\Roaming\npm\node_modules\@codedoc\cli\node_modules\source-map-support\source-map-support.js:568:25)
    at Module.m._compile (C:\Users\TWILLI~1\AppData\Local\Temp\ts-node-dev-hook-6168886849865232.js:69:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at require.extensions..jsx.require.extensions..js (C:\Users\TWILLI~1\AppData\Local\Temp\ts-node-dev-hook-6168886849865232.js:114:20)
    at require.extensions.<computed> (C:\Users\TWILLI~1\AppData\Local\Temp\ts-node-dev-hook-6168886849865232.js:71:20)
    at Object.nodeDevHook [as .ts] (C:\Users\twilliams\AppData\Roaming\npm\node_modules\@codedoc\cli\node_modules\ts-node-dev\lib\hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:986:32)
[ERROR] 09:51:43 TypeError: merge is not a function
```

Any ideas how to solve this?

**Comment by loreanvictor** [comment]
I suspect I forgot to update `@types/webpack-merge` (or whatever typedef library there is for webpack merge) accordingly? I'll take a look tomorrow.

**Comment by loreanvictor** [comment]
this should be fixed via `@codedoc/core@0.3.2`

**Comment by TysonMN** [comment]
Yes, that was it.  Thanks for the update! :)

**Comment by loreanvictor** [comment]
thanks for the heads up! 😅
