### ISSUE TITLE
github action failure

### ISSUE THREAD

**Issue by nakednous** [CONNECT-platform/codedoc#142]
Hello,

recently my github deplay action began to fail. It was to work fine.  Here's part of my [log](https://github.com/objetos/p5.quadrille.js/actions/runs/3953964466/jobs/6770788437):

```sh
Entrypoint main = codedoc-bundle.js
  [4] ./.codedoc/node_modules/rxjs/_esm5/internal/Subscriber.js 8.44 KiB {0} [built]
  [6] ./.codedoc/node_modules/rxjs/_esm5/index.js 3.33 KiB [built]
  [7] ./.codedoc/node_modules/rxjs/_esm5/internal/Observable.js + 3 modules 5.86 KiB {0} [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/util/pipe.js 565 bytes [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/Observable.js 3.95 KiB [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/util/canReportError.js 580 bytes [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/util/toSubscriber.js 776 bytes [built]
  [8] ./.codedoc/node_modules/@connectv/core/dist/es6/index.js 125 bytes [built]
 [11] ./.codedoc/node_modules/rxjs/_esm5/internal/Subscription.js + 1 modules 5.8 KiB {0} [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/util/UnsubscriptionError.js 707 bytes [built]
      | ./.codedoc/node_modules/rxjs/_esm5/internal/Subscription.js 5.09 KiB [built]
 [12] ./.codedoc/node_modules/@connectv/sdh/dist/es6/dynamic/transport/index.js 216 bytes [built]
 [14] ./.codedoc/node_modules/rxjs/_esm5/operators/index.js 6.15 KiB [built]
 [16] ./.codedoc/node_modules/rxjs/_esm5/internal/config.js 859 bytes {0} [built]
 [20] ./.codedoc/node_modules/@connectv/html/dist/es6/index.js 224 bytes [built]
 [25] ./.codedoc/node_modules/@connectv/jss-theme/dist/es6/index.js 90 bytes [built]
[140] ./.codedoc/content/theme.ts 373 bytes {0} [built] [failed] [1 error]
[144] ./.codedoc/node_modules/color/index.js 10.9 KiB {0} [built]
[146] ./.codedoc/node_modules/@codedoc/core/dist/es6/components/darkmode/darklight/index.js 1.46 KiB [built]
[231] ./dist/docs/assets/codedoc-bundle.entry.js + 204 modules 392 KiB {0} [built]
      | ./dist/docs/assets/codedoc-bundle.entry.js 4.69 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/transport/renderer.js 500 bytes [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/transport/setup-jss.js 472 bytes [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/formula/zoom-on-formula.js 1.24 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/code/smart-copy.js 1.42 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/code/selection.js 5.03 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/code/same-line-length.js 818 bytes [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/code/line-hint/index.js 1.77 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/transport/config.js 359 bytes [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/code/line-ref/index.js 2.07 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/heading/copy-headings.js 1.89 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/page/contentnav/highlight.js 2.06 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/transport/deferred-iframe.js 607 bytes [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/transport/smooth-loading.js 4.66 KiB [built]
      | ./.codedoc/node_modules/@codedoc/core/dist/es6/components/page/toc/toc-highlight.js 1.33 KiB [built]
      |     + 190 hidden modules
[236] ./.codedoc/node_modules/rxjs/_esm5/ajax/index.js 237 bytes [built]
    + 386 hidden modules

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in ./.codedoc/content/theme.ts
Module build failed (from ./node_modules/ts-loader/index.js):
TypeError: loaderContext.getOptions is not a function
    at getLoaderOptions (/home/runner/work/p5.quadrille.js/p5.quadrille.js/node_modules/ts-loader/dist/index.js:91:41)
    at Object.loader (/home/runner/work/p5.quadrille.js/p5.quadrille.js/node_modules/ts-loader/dist/index.js:14:21)
 @ ./dist/docs/assets/codedoc-bundle.entry.js 3:0-107 3:107-119
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
# Build Failed.

Error: Process completed with exit code 1.
```

Thoughts are much appreciated

**Comment by loreanvictor** [comment]
which version of codedoc are you on?

**Comment by nakednous** [comment]
```sh
# @codedoc/cli version 0.3.0 ...................................... latest: 0.3.0
# @codedoc/core version: 0.2.24 ................................... latest: 0.3.2
```

**Comment by nakednous** [comment]
updating it to `0.3.2` fixed the issue. Thanks

**Comment by nakednous** [comment]
the github action started failing again. Here's the [log](https://github.com/objetos/p5.quadrille.js/actions/runs/5674462999/job/15378037887).

I have have the same codedoc version which seems latest:

```sh
# @codedoc/cli version 0.3.0 ...................................... latest: 0.3.0
# @codedoc/core version: 0.3.2 .................................... latest: 0.3.2
```

Should I wait till the next codedoc release?

**Comment by nakednous** [comment]
or there's a quicker fix?
