### ISSUE TITLE
update latest fails in Mintty terminal from lack of permissions

### ISSUE THREAD

**Issue by bender2k14** [CONNECT-platform/codedoc#22]
I like to use the terminal Mintty (currently have version 2.9.6), which I open via GitKraken.

After executing `npm i -g @codedoc/cli@0.2.0`, I have the following installed
- `codedoc/cli` 0.2.0
- `codedoc/core` 0.1.63

Then executing `codedoc update latest` crashes.  After which, `codedoc` isn't even installed.

```
twilliams@EDMONDS MINGW64 /c/Code/Blogs/tyson-williams-blog (master)
$ codedoc version

# Fetching version info ...
# @codedoc/cli version 0.2.0 ...................................... latest: 0.2.0
# @codedoc/core version: 0.1.63 ................................... latest: 0.2.0

# WARNING: some packages are missing or need update.
# Please run codedoc update


twilliams@EDMONDS MINGW64 /c/Code/Blogs/tyson-williams-blog (master)
$ codedoc update latest

# Updating CLI to latest version ...
npm ERR! code EPERM
npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\twilliams\AppData\Roaming\npm\codedoc'
npm ERR!     at isClobberable (C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:55:3)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:38:27
npm ERR!     at Array.forEach (<anonymous>)
npm ERR!     at binLink (C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:38:13)
npm ERR!     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR!     at ret (eval at makeNodePromisifiedEval (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:11:39)
npm ERR!     at linkBin (C:\Program Files\nodejs\node_modules\npm\node_modules\bin-links\index.js:126:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\bin-links\index.js:91:12
npm ERR!     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR!     at MappingPromiseArray._promiseFulfilled (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\map.js:61:38)
npm ERR!     at MappingPromiseArray.PromiseArray._iterate (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:114:31)
npm ERR!     at MappingPromiseArray.init (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:78:10)
npm ERR!     at MappingPromiseArray._asyncInit (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\map.js:30:10)
npm ERR!     at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:142:12)
npm ERR!     at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
npm ERR!     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
npm ERR!  OperationalError: EPERM: operation not permitted, open 'C:\Users\twilliams\AppData\Roaming\npm\codedoc'
npm ERR!     at isClobberable (C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:55:3)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:38:27
npm ERR!     at Array.forEach (<anonymous>)
npm ERR!     at binLink (C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:38:13)
npm ERR!     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR!     at ret (eval at makeNodePromisifiedEval (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:11:39)
npm ERR!     at linkBin (C:\Program Files\nodejs\node_modules\npm\node_modules\bin-links\index.js:126:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\bin-links\index.js:91:12
npm ERR!     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR!     at MappingPromiseArray._promiseFulfilled (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\map.js:61:38)
npm ERR!     at MappingPromiseArray.PromiseArray._iterate (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:114:31)
npm ERR!     at MappingPromiseArray.init (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:78:10)
npm ERR!     at MappingPromiseArray._asyncInit (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\map.js:30:10)
npm ERR!     at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:142:12)
npm ERR!     at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
npm ERR!     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5) {
npm ERR!   cause: Error: EPERM: operation not permitted, open 'C:\Users\twilliams\AppData\Roaming\npm\codedoc'
npm ERR!       at isClobberable (C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:55:3)
npm ERR!       at C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:38:27
npm ERR!       at Array.forEach (<anonymous>)
npm ERR!       at binLink (C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:38:13)
npm ERR!       at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR!       at ret (eval at makeNodePromisifiedEval (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:11:39)
npm ERR!       at linkBin (C:\Program Files\nodejs\node_modules\npm\node_modules\bin-links\index.js:126:10)
npm ERR!       at C:\Program Files\nodejs\node_modules\npm\node_modules\bin-links\index.js:91:12
npm ERR!       at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR!       at MappingPromiseArray._promiseFulfilled (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\map.js:61:38)
npm ERR!       at MappingPromiseArray.PromiseArray._iterate (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:114:31)
npm ERR!       at MappingPromiseArray.init (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:78:10)
npm ERR!       at MappingPromiseArray._asyncInit (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\map.js:30:10)
npm ERR!       at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:142:12)
npm ERR!       at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
npm ERR!       at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5) {
npm ERR!     code: 'EPERM'
npm ERR!   },
npm ERR!   code: 'EPERM'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\twilliams\AppData\Roaming\npm-cache\_logs\2020-06-11T12_01_36_759Z-debug.log
(node:15252) UnhandledPromiseRejectionWarning: undefined
(node:15252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

twilliams@EDMONDS MINGW64 /c/Code/Blogs/tyson-williams-blog (master)
$ codedoc version
bash: /c/Users/twilliams/AppData/Roaming/npm/codedoc: No such file or directory
```

The file mentioned in...
```
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\twilliams\AppData\Roaming\npm-cache\_logs\2020-06-11T12_01_36_759Z-debug.log
```

...is [available here](https://github.com/CONNECT-platform/codedoc/files/4764624/2020-06-11T12_01_36_759Z-debug.log).

**Comment by loreanvictor** [comment]
seems like the cli is unable to self-update on Windows. @bender2k14 could you install a lower version of the cli (e.g. `0.1.3`), and then try `codedoc update` to see if it can conduct soft self-updates? you don't need to even be in a CODEDOC project folder for that test.

I am trying to assess whether this issue is only limited to the major update mechanism or does it also affect minor updates of the CLI.

**Comment by bender2k14** [comment]
>  @bender2k14 could you install a lower version of the cli (e.g. `0.1.3`), and then try `codedoc update` to see if it can conduct soft self-updates?

Of course.  Anything I can do to help :)

Seems to fail in the same way.

```
twilliams@EDMONDS MINGW64 /c/Code/Blogs/tyson-williams-blog (master)
$ npm i -g @codedoc/cli@0.1.3
C:\Users\twilliams\AppData\Roaming\npm\codedoc -> C:\Users\twilliams\AppData\Roaming\npm\node_modules\@codedoc\cli\src\index.js
+ @codedoc/cli@0.1.3
added 94 packages from 92 contributors in 9.9s

twilliams@EDMONDS MINGW64 /c/Code/Blogs/tyson-williams-blog (master)
$ codedoc update

# Updating CLI ...
npm ERR! code EPERM
npm ERR! Error: EPERM: operation not permitted, open 'C:\Users\twilliams\AppData\Roaming\npm\codedoc'
npm ERR!     at isClobberable (C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:55:3)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:38:27
npm ERR!     at Array.forEach (<anonymous>)
npm ERR!     at binLink (C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:38:13)
npm ERR!     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR!     at ret (eval at makeNodePromisifiedEval (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:11:39)
npm ERR!     at linkBin (C:\Program Files\nodejs\node_modules\npm\node_modules\bin-links\index.js:126:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\bin-links\index.js:91:12
npm ERR!     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR!     at MappingPromiseArray._promiseFulfilled (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\map.js:61:38)
npm ERR!     at MappingPromiseArray.PromiseArray._iterate (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:114:31)
npm ERR!     at MappingPromiseArray.init (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:78:10)
npm ERR!     at MappingPromiseArray._asyncInit (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\map.js:30:10)
npm ERR!     at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:142:12)
npm ERR!     at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
npm ERR!     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5)
npm ERR!  OperationalError: EPERM: operation not permitted, open 'C:\Users\twilliams\AppData\Roaming\npm\codedoc'
npm ERR!     at isClobberable (C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:55:3)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:38:27
npm ERR!     at Array.forEach (<anonymous>)
npm ERR!     at binLink (C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:38:13)
npm ERR!     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR!     at ret (eval at makeNodePromisifiedEval (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:11:39)
npm ERR!     at linkBin (C:\Program Files\nodejs\node_modules\npm\node_modules\bin-links\index.js:126:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\node_modules\bin-links\index.js:91:12
npm ERR!     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR!     at MappingPromiseArray._promiseFulfilled (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\map.js:61:38)
npm ERR!     at MappingPromiseArray.PromiseArray._iterate (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:114:31)
npm ERR!     at MappingPromiseArray.init (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:78:10)
npm ERR!     at MappingPromiseArray._asyncInit (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\map.js:30:10)
npm ERR!     at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:142:12)
npm ERR!     at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
npm ERR!     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5) {
npm ERR!   cause: Error: EPERM: operation not permitted, open 'C:\Users\twilliams\AppData\Roaming\npm\codedoc'
npm ERR!       at isClobberable (C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:55:3)
npm ERR!       at C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:38:27
npm ERR!       at Array.forEach (<anonymous>)
npm ERR!       at binLink (C:\Program Files\nodejs\node_modules\npm\node_modules\gentle-fs\lib\bin-link.js:38:13)
npm ERR!       at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR!       at ret (eval at makeNodePromisifiedEval (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promisify.js:184:12), <anonymous>:11:39)
npm ERR!       at linkBin (C:\Program Files\nodejs\node_modules\npm\node_modules\bin-links\index.js:126:10)
npm ERR!       at C:\Program Files\nodejs\node_modules\npm\node_modules\bin-links\index.js:91:12
npm ERR!       at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
npm ERR!       at MappingPromiseArray._promiseFulfilled (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\map.js:61:38)
npm ERR!       at MappingPromiseArray.PromiseArray._iterate (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:114:31)
npm ERR!       at MappingPromiseArray.init (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise_array.js:78:10)
npm ERR!       at MappingPromiseArray._asyncInit (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\map.js:30:10)
npm ERR!       at _drainQueueStep (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:142:12)
npm ERR!       at _drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:131:9)
npm ERR!       at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:147:5) {
npm ERR!     code: 'EPERM'
npm ERR!   },
npm ERR!   code: 'EPERM'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\twilliams\AppData\Roaming\npm-cache\_logs\2020-06-11T13_31_51_931Z-debug.log
(node:8160) UnhandledPromiseRejectionWarning: undefined
(node:8160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The file mentioned in...
```
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\twilliams\AppData\Roaming\npm-cache\_logs\2020-06-11T12_01_36_759Z-debug.log
```

...is [available here](https://github.com/CONNECT-platform/codedoc/files/4765046/2020-06-11T13_31_51_931Z-debug.log).

**Comment by loreanvictor** [comment]
@bender2k14 thanks a lot! I will disable the self-update mechanism for windows and roll out a new version of the CLI.

**Comment by loreanvictor** [comment]
@bender2k14 ok from another test on a Windows 7 machine (`npm v 6.14.4`, `node v 12.8.0`) the self-update mechanism seems to work fine (both soft-update and update-to-latest). since the node version and npm version are matching, maybe the shell you are running the command in lacks some permissions? I executed the command in the default Command Prompt.

**Comment by bender2k14** [comment]
Using the default Command Prompt worked.  Good suggestion.  I am very happy to have this workaround.

In the meantime, I might not try to find a solution to this problem so quickly.

I will update my original comment and the title with the specific terminal that is causing the problem.

```
C:\Code\Blogs\tyson-williams-blog>codedoc version

# Fetching version info ...
# @codedoc/cli version 0.2.0 ...................................... latest: 0.2.0
# @codedoc/core version: 0.1.62 ................................... latest: 0.2.0

# WARNING: some packages are missing or need update.
# Please run codedoc update


C:\Code\Blogs\tyson-williams-blog>codedoc update latest

# Updating CLI to latest version ...
C:\Users\twilliams\AppData\Roaming\npm\codedoc -> C:\Users\twilliams\AppData\Roaming\npm\node_modules\@codedoc\cli\src\index.js
+ @codedoc/cli@0.2.0
updated 1 package in 3.484s
# Updating local codedoc installation to latest version ...
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.18.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @codedoc/coding-blog-plugin@0.1.3 requires a peer of @codedoc/core@^0.1.59 but none is installed. You must install peer dependencies yourself.
npm WARN ts-loader@6.2.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN .codedoc No description
npm WARN .codedoc No repository field.
npm WARN .codedoc No license field.

+ @codedoc/core@0.2.0
added 1 package from 1 contributor, updated 2 packages and audited 577 packages in 25.011s
found 0 vulnerabilities



C:\Code\Blogs\tyson-williams-blog>codedoc version

# Fetching version info ...
# @codedoc/cli version 0.2.0 ...................................... latest: 0.2.0
# @codedoc/core version: 0.2.0 .................................... latest: 0.2.0
```

**Comment by loreanvictor** [comment]
I am adding a `--local` option to `update` and `update latest` commands, which would skip updating the CLI. this should allow updating the local codedoc installation in environments that lack permission to update the CLI itself.

**Comment by loreanvictor** [comment]
[Updated the cli](https://github.com/CONNECT-platform/codedoc-cli/commit/5074b8620599216deb04a4ec52763a037a7cd061d), deployed via `@codedoc/cli@0.2.1`. Also [updated the docs](https://codedoc.cc/docs/cli#update-permissions).

**Comment by bender2k14** [comment]
How can I test this?  Is it possible to have version 0.2.1 of the CLI but version 0.1.63 of Core?  I tried uninstalling and reinstalling Core in a few different ways, but I was never able to get that situation.

**Comment by loreanvictor** [comment]
Yes and it should work properly. You can simply install `@codedoc/core@0.1.63`, i.e.

```bash
cd .codedoc
npm install @codedoc/core@0.1.63
```

**Comment by bender2k14** [comment]
Thanks for that.

Everything works :)

And I am getting smarter too.  I now understand that the `-g` in `npm i -g @codedoc/cli@0.2.1` is causing a global installation.  And that is why you called the option `--local`, because `@codedoc/core@0.1.63` is not installed globally but in my repo's `.codedoc` folder.

Great workaround!
