### ISSUE TITLE
theme.ts error: Cannot find module 'typescript'

### ISSUE THREAD

**Issue by psydvl** [CONNECT-platform/codedoc#72]
node v12.18.4
npm 6.14.6
```
> codedoc serve
```

```
ERROR in ./.codedoc/content/theme.ts
Module build failed (from ./.codedoc/node_modules/ts-loader/index.js):
Error: Cannot find module 'typescript'
Require stack:
- /home/nixi/work/project/site/.codedoc/node_modules/ts-loader/dist/utils.js
- /home/nixi/work/project/site/.codedoc/node_modules/ts-loader/dist/after-compile.js
- /home/nixi/work/project/site/.codedoc/node_modules/ts-loader/dist/instances.js
- /home/nixi/work/project/site/.codedoc/node_modules/ts-loader/dist/index.js
- /home/nixi/work/project/site/.codedoc/node_modules/ts-loader/index.js
- /home/nixi/work/project/site/.codedoc/node_modules/loader-runner/lib/loadLoader.js
- /home/nixi/work/project/site/.codedoc/node_modules/loader-runner/lib/LoaderRunner.js
- /home/nixi/work/project/site/.codedoc/node_modules/webpack/lib/NormalModule.js
- /home/nixi/work/project/site/.codedoc/node_modules/webpack/lib/NormalModuleFactory.js
- /home/nixi/work/project/site/.codedoc/node_modules/webpack/lib/Compiler.js
- /home/nixi/work/project/site/.codedoc/node_modules/webpack/lib/webpack.js
- /home/nixi/work/project/site/.codedoc/node_modules/@connectv/sdh/dist/es5/dynamic/webpack.js
- /home/nixi/work/project/site/.codedoc/node_modules/@connectv/sdh/dist/es5/dynamic/pack.js
- /home/nixi/work/project/site/.codedoc/node_modules/@connectv/sdh/dist/es5/dynamic/index.js
- /home/nixi/work/project/site/.codedoc/node_modules/@connectv/sdh/dist/es5/index.js
- /home/nixi/work/project/site/.codedoc/node_modules/@codedoc/core/dist/es5/build/index.js
- /home/nixi/work/project/site/.codedoc/node_modules/@codedoc/core/dist/es5/index.js
- /home/nixi/work/project/site/.codedoc/serve.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/nixi/work/project/site/.codedoc/node_modules/ts-loader/dist/utils.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Module._compile (/home/nixi/.config/yarn/global/node_modules/source-map-support/source-map-support.js:547:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.nodeDevHook [as .js] (/home/nixi/.config/yarn/global/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:985:32)
 @ ./docs/assets/codedoc-bundle.entry.js 3:0-86 3:86-98
(node:110631) UnhandledPromiseRejectionWarning: [object Object]
(node:110631) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:110631) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by TysonMN** [comment]
> `Error: Cannot find module 'typescript'`

Do you have TypeScript installed?  If so, what version do you have?

**Comment by loreanvictor** [comment]
@psydvl seems like under some strange circumstances either `typescript` was not installed for you, despite it [being a direct dependency of `@codedoc/cli`](https://github.com/CONNECT-platform/codedoc-cli/blob/7fe4d6d852c658b92c6a59c680f749178cd8ddd7/package.json#L35), or for whatever reason typescript is masked from the local codedoc code.

Aside from checking what @TysonMN suggested, I would also recommend running the docker version (`docker-compose up` should do the trick) if you have docker, to see if you get the same issue or not. Additionally, some information about your environment would be pretty helpful.

**Comment by psydvl** [comment]
Ok, I solved this:
codedoc installed global using `yarn` so typescript not provided for npm

**Comment by psydvl** [comment]
May be `yarn` support will be good feature?
