### ISSUE TITLE
Unknown programming language in markdown results in exception

### ISSUE THREAD

**Issue by LukasForst** [CONNECT-platform/codedoc#8]
When I create code block with programming language annotation, which is not known to `prism`, the build throws exception.

For example using:  "_```log_" results in following exception

```
Language does not exist: log
TypeError: Cannot read property 'rest' of undefined
    at Object.tokenize (/Users/lukas/repos/blog/.codedoc/node_modules/prismjs/prism.js:340:22)
    at Object.highlight (/Users/lukas/repos/blog/.codedoc/node_modules/prismjs/prism.js:334:18)
    at Object.Code (/Users/lukas/repos/blog/.codedoc/node_modules/@codedoc/core/src/components/code/index.tsx:49:28)
    at ComponentPlugin.create (/Users/lukas/repos/blog/.codedoc/node_modules/@connectv/html/src/renderer/plugin/component/component.ts:39:25)
    at /Users/lukas/repos/blog/.codedoc/node_modules/@connectv/html/src/renderer/extensible-renderer.ts:45:77
    at Array.some (<anonymous>)
    at ExtensibleRenderer.create (/Users/lukas/repos/blog/.codedoc/node_modules/@connectv/html/src/renderer/extensible-renderer.ts:45:18)
    at Parser.tok (/Users/lukas/repos/blog/.codedoc/node_modules/@connectv/marked/src/parser.tsx:75:16)
    at Parser.parse (/Users/lukas/repos/blog/.codedoc/node_modules/@connectv/marked/src/parser.tsx:33:28)
    at /Users/lukas/repos/blog/.codedoc/node_modules/@connectv/marked/src/index.ts:13:19
[ERROR] 19:34:45 TypeError: Cannot read property 'rest' of undefined
```

I would suggest not throwing exception, but rather to fallback on the default - non-highlighted  code block.
Why - for example new language XY is published and I want to write snippets - `prism` does not support the language yet, but in few months it will. In case of throwing exception, I'd need to rewrite my old snippets to be properly highlighted, but if there's a fallback, I don't need to do anything apart from upgrading `prism`.

**Comment by loreanvictor** [comment]
Yes that is true. On the other hand, throwing an error stops typos in programming languages. Since newer languages occur less often, I am not sure it would be useful to allow errors slip by in exchange for making codedoc more convenient for those scenarios.

How about allowing a flag for bypassing errors on unrecognized languages? i.e.

````
```XY
xy +> xxy
```
````

would throw the same error, but

````
```XY | --safe
xy +> xxy
```
````

wouldn't.

**Comment by LukasForst** [comment]
that's actually a good compromise 👍

**Comment by loreanvictor** [comment]
fixed in [this commit](https://github.com/CONNECT-platform/codedoc/commit/3f8007a9e07d4c5b225a5cf7c03ec063d9420d35), deployed via `@codedoc/core@0.1.38`.

I added `--safe-highlight` flag for this specific purpose, also a more easily understandable error message that guides to prism's supported language page and informs about this flag as well.

Will keep the issue open until it is added to the docs as well.

**Comment by loreanvictor** [comment]
added [a section to the docs](https://codedoc.cc/docs/code/overview#unsupported-languages) as well.
